from datetime import datetime, timedelta, timezone
from decimal import Decimal

from sqlalchemy import select

from app.database import SessionLocal
from app.models import CallRecord, Load


def seed() -> None:
    db = SessionLocal()
    try:
        existing = db.scalar(select(Load.id).limit(1))
        if not existing:
            now = datetime.now(timezone.utc)
            loads = [
                {
                    "load_id": "LD-1001",
                    "origin": "Dallas, TX",
                    "destination": "Atlanta, GA",
                    "pickup_datetime": now + timedelta(days=1, hours=9),
                    "delivery_datetime": now + timedelta(days=3, hours=14),
                    "equipment_type": "Dry Van",
                    "loadboard_rate": Decimal("2400"),
                    "notes": "No-touch freight. Appointment required.",
                    "weight": 38000,
                    "commodity_type": "Packaged food",
                    "num_of_pieces": 22,
                    "miles": 781,
                    "dimensions": "53ft trailer",
                },
                {
                    "load_id": "LD-1002",
                    "origin": "Chicago, IL",
                    "destination": "Denver, CO",
                    "pickup_datetime": now + timedelta(days=2, hours=8),
                    "delivery_datetime": now + timedelta(days=4, hours=16),
                    "equipment_type": "Reefer",
                    "loadboard_rate": Decimal("2850"),
                    "notes": "Temp setpoint 34F.",
                    "weight": 41000,
                    "commodity_type": "Dairy",
                    "num_of_pieces": 28,
                    "miles": 1004,
                    "dimensions": "53ft reefer",
                },
                {
                    "load_id": "LD-1003",
                    "origin": "Los Angeles, CA",
                    "destination": "Phoenix, AZ",
                    "pickup_datetime": now + timedelta(days=1, hours=7),
                    "delivery_datetime": now + timedelta(days=2, hours=13),
                    "equipment_type": "Dry Van",
                    "loadboard_rate": Decimal("1650"),
                    "notes": "Drop and hook.",
                    "weight": 26000,
                    "commodity_type": "Consumer goods",
                    "num_of_pieces": 18,
                    "miles": 372,
                    "dimensions": "53ft trailer",
                },
                {
                    "load_id": "LD-1004",
                    "origin": "Memphis, TN",
                    "destination": "Charlotte, NC",
                    "pickup_datetime": now + timedelta(days=3, hours=10),
                    "delivery_datetime": now + timedelta(days=5, hours=9),
                    "equipment_type": "Flatbed",
                    "loadboard_rate": Decimal("2200"),
                    "notes": "Tarp required.",
                    "weight": 42000,
                    "commodity_type": "Steel coils",
                    "num_of_pieces": 14,
                    "miles": 625,
                    "dimensions": "48ft flatbed",
                },
                {
                    "load_id": "LD-1005",
                    "origin": "Columbus, OH",
                    "destination": "Newark, NJ",
                    "pickup_datetime": now + timedelta(days=2, hours=11),
                    "delivery_datetime": now + timedelta(days=4, hours=8),
                    "equipment_type": "Dry Van",
                    "loadboard_rate": Decimal("2050"),
                    "notes": "Live unload.",
                    "weight": 36000,
                    "commodity_type": "Retail freight",
                    "num_of_pieces": 24,
                    "miles": 526,
                    "dimensions": "53ft trailer",
                },
                {
                    "load_id": "LD-1006",
                    "origin": "Seattle, WA",
                    "destination": "Sacramento, CA",
                    "pickup_datetime": now + timedelta(days=1, hours=6),
                    "delivery_datetime": now + timedelta(days=3, hours=17),
                    "equipment_type": "Reefer",
                    "loadboard_rate": Decimal("2750"),
                    "notes": "Produce, continuous run.",
                    "weight": 39000,
                    "commodity_type": "Fresh produce",
                    "num_of_pieces": 30,
                    "miles": 755,
                    "dimensions": "53ft reefer",
                },
                {
                    "load_id": "LD-1007",
                    "origin": "Kansas City, MO",
                    "destination": "Minneapolis, MN",
                    "pickup_datetime": now + timedelta(days=2, hours=9),
                    "delivery_datetime": now + timedelta(days=3, hours=20),
                    "equipment_type": "Dry Van",
                    "loadboard_rate": Decimal("1900"),
                    "notes": "FCFS pickup.",
                    "weight": 33000,
                    "commodity_type": "Paper products",
                    "num_of_pieces": 20,
                    "miles": 438,
                    "dimensions": "53ft trailer",
                },
                {
                    "load_id": "LD-1008",
                    "origin": "Houston, TX",
                    "destination": "New Orleans, LA",
                    "pickup_datetime": now + timedelta(days=1, hours=12),
                    "delivery_datetime": now + timedelta(days=2, hours=10),
                    "equipment_type": "Flatbed",
                    "loadboard_rate": Decimal("1500"),
                    "notes": "Straps required.",
                    "weight": 28000,
                    "commodity_type": "Industrial equipment",
                    "num_of_pieces": 10,
                    "miles": 347,
                    "dimensions": "48ft flatbed",
                },
                {
                    "load_id": "LD-1009",
                    "origin": "Indianapolis, IN",
                    "destination": "Nashville, TN",
                    "pickup_datetime": now + timedelta(days=3, hours=8),
                    "delivery_datetime": now + timedelta(days=4, hours=13),
                    "equipment_type": "Dry Van",
                    "loadboard_rate": Decimal("1400"),
                    "notes": "Pallet exchange.",
                    "weight": 25000,
                    "commodity_type": "Beverages",
                    "num_of_pieces": 16,
                    "miles": 290,
                    "dimensions": "53ft trailer",
                },
                {
                    "load_id": "LD-1010",
                    "origin": "Salt Lake City, UT",
                    "destination": "Las Vegas, NV",
                    "pickup_datetime": now + timedelta(days=2, hours=5),
                    "delivery_datetime": now + timedelta(days=3, hours=15),
                    "equipment_type": "Reefer",
                    "loadboard_rate": Decimal("1700"),
                    "notes": "Frozen goods at -10F.",
                    "weight": 34000,
                    "commodity_type": "Frozen food",
                    "num_of_pieces": 19,
                    "miles": 420,
                    "dimensions": "53ft reefer",
                },
            ]
            db.add_all([Load(**row, status="available") for row in loads])

        existing_calls = db.scalar(select(CallRecord.id).limit(1))
        if not existing_calls:
            sample_calls = [
                CallRecord(
                    happyrobot_run_id="run_1001",
                    session_id="session_1001",
                    mc_number="123456",
                    carrier_name="ABC Trucking",
                    load_id="LD-1001",
                    origin="Dallas, TX",
                    destination="Atlanta, GA",
                    equipment_type="Dry Van",
                    loadboard_rate=Decimal("2400"),
                    final_offer=Decimal("2525"),
                    outcome="booked",
                    sentiment="positive",
                    call_summary="Carrier verified and booked at $2,525.",
                    transcript="Carrier asked for Dallas to Atlanta load and accepted after one counter.",
                    negotiation_rounds=2,
                ),
                CallRecord(
                    happyrobot_run_id="run_1002",
                    session_id="session_1002",
                    mc_number="222333",
                    carrier_name="Prime Freight",
                    load_id="LD-1002",
                    origin="Chicago, IL",
                    destination="Denver, CO",
                    equipment_type="Reefer",
                    loadboard_rate=Decimal("2850"),
                    final_offer=Decimal("3020"),
                    outcome="booked",
                    sentiment="neutral",
                    call_summary="Carrier accepted final counter after 3 rounds.",
                    transcript="Carrier pushed above max, accepted cap in final round.",
                    negotiation_rounds=3,
                ),
                CallRecord(
                    happyrobot_run_id="run_1003",
                    session_id="session_1003",
                    mc_number="999888",
                    carrier_name="Legacy Lines",
                    load_id="LD-1008",
                    origin="Houston, TX",
                    destination="New Orleans, LA",
                    equipment_type="Flatbed",
                    loadboard_rate=Decimal("1500"),
                    final_offer=Decimal("1850"),
                    outcome="declined",
                    sentiment="negative",
                    call_summary="No rate agreement reached by round 3.",
                    transcript="Carrier insisted on $1,850. System declined.",
                    negotiation_rounds=3,
                ),
                CallRecord(
                    happyrobot_run_id="run_1004",
                    session_id="session_1004",
                    mc_number="666777",
                    carrier_name="Blue Ridge Logistics",
                    load_id="LD-1005",
                    origin="Columbus, OH",
                    destination="Newark, NJ",
                    equipment_type="Dry Van",
                    loadboard_rate=Decimal("2050"),
                    final_offer=None,
                    outcome="ineligible",
                    sentiment="neutral",
                    call_summary="Carrier failed authority check.",
                    transcript="Verification returned inactive authority.",
                    negotiation_rounds=0,
                ),
                CallRecord(
                    happyrobot_run_id="run_1005",
                    session_id="session_1005",
                    mc_number="444555",
                    carrier_name="Evergreen Carriers",
                    load_id=None,
                    origin="Miami, FL",
                    destination="Atlanta, GA",
                    equipment_type="Dry Van",
                    loadboard_rate=None,
                    final_offer=None,
                    outcome="no_load_found",
                    sentiment="neutral",
                    call_summary="No matching load found on requested lane.",
                    transcript="Carrier requested Miami outbound load not available.",
                    negotiation_rounds=0,
                ),
            ]
            db.add_all(sample_calls)

        db.commit()
    finally:
        db.close()


if __name__ == "__main__":
    seed()
